/**
 * REDUX STORE CONFIGURATION
 * 
 * This file sets up the Redux store using Redux Toolkit.
 * 
 * WHAT IS REDUX?
 * Redux is a state management library that helps manage application-wide state.
 * Instead of passing props through many components (prop drilling), Redux provides
 * a central "store" where any component can access or update state.
 * 
 * REDUX TOOLKIT:
 * Redux Toolkit (RTK) is the official, opinionated way to write Redux logic.
 * It simplifies common Redux patterns and reduces boilerplate code.
 * 
 * STORE STRUCTURE:
 * - store: The central state container
 * - slices: Logical divisions of state (characters, locations, episodes)
 * - actions: Functions that describe what happened (auto-generated by RTK)
 * - reducers: Functions that specify how state updates (auto-generated by RTK)
 */

import { configureStore } from '@reduxjs/toolkit';
import charactersReducer from './slices/charactersSlice';

/**
 * Configure and create the Redux store
 * 
 * The store is the single source of truth for our application state.
 * All components can read from and write to this store.
 * 
 * @returns {Object} Configured Redux store
 */
export const store = configureStore({
  reducer: {
    // Each slice manages its own part of the state
    // Access via: state.characters, state.locations, etc.
    characters: charactersReducer,
    // Future slices can be added here:
    // locations: locationsReducer,
    // episodes: episodesReducer,
  },
  
  // Redux Toolkit includes helpful defaults:
  // - Redux DevTools Extension support
  // - Thunk middleware for async actions
  // - Immutability checks in development
});

/**
 * Type definitions for TypeScript users (documented here for learning)
 * 
 * RootState: The type of the entire Redux state tree
 * AppDispatch: The type of the dispatch function
 * 
 * These are useful for TypeScript, but in JavaScript we use JSDoc comments.
 */
